name: Publish to GitHub Packages

on:
  push:
    branches: [main]
    paths:
      - 'agent-react-hook/**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@janardhanhere'
      - name: Install dependencies
        run: cd agent-react-hook && npm ci
      - name: Build
        run: cd agent-react-hook && npm run build
      - name: Publish to GitHub Packages
        run: cd agent-react-hook && npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
